#!/bin/bash

COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
REGEX="^[A-Z]+-\d+:.+$"

echo "Commit Message Hook: Checking commit message..."

if ! echo "$COMMIT_MSG" | grep -qE "$REGEX"; then
    echo "Commit Message does not follow the required format!"
    echo "Expected Format: ABC-123: Your commit message"
    exit 1
fi

echo "Commit Message Validated"
exit 0