#!/bin/sh
# Commit message hook to prevent empty commit messages

echo "Commit Message Hook: Checking commit message..."

COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
REGEX="^[A-Z]+-\d+:.+$"

# Check if commit message is empty or only whitespace
if [ -z "$COMMIT_MSG" ] || [ -z "$(echo "$COMMIT_MSG" | tr -d '[:space:]')" ]; then
	echo "Error: Commit Message is empty or only whitespace."
	echo "Please provide a valid commit message."
	exit 1
fi

# Check if commit message matches the regex pattern
if ! echo "$COMMIT_MSG" | grep -qE "$REGEX"; then
    echo "Commit Message does not follow the required format."
    echo "Expected Format: ABC-123: Your commit message"
    exit 1
fi


echo "Commit Message Validated."
exit 0