#!/bin/sh
# Commit message hook to prevent empty commit messages

echo "Commit Message Hook: Checking commit message..."

COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
REGEX="^[A-Z]+-\d+:.+$"
MAX_LENGTH=64
MIN_LENGTH=10
COMMIT_LENGTH=${#COMMIT_MSG}

# Check if commit message is empty or only whitespace
if [ -z "$COMMIT_MSG" ] || [ -z "$(echo "$COMMIT_MSG" | tr -d '[:space:]')" ]; then
	echo "Error: Commit Message is empty or only whitespace."
	echo "Please provide a valid commit message."
	exit 1
fi

# Check if commit message matches the regex pattern
if ! echo "$COMMIT_MSG" | grep -qE "$REGEX"; then
    echo "Error: Commit Message does not follow the required format."
    echo "Expected Format: ABC-123: Your commit message"
    exit 1
fi

# Check if commit message is longer than 64 characters
if [ "$COMMIT_LENGTH" -gt "$MAX_LENGTH" ]; then
    echo "Error: Commit message is too long. ($COMMIT_LENGTH characters)."
    echo "Please keep it under $MAX_LENGTH characters."
    exit 1
fi

# Check if commit message is shorter than 10 characters
# Dosent block, just warns
if [ "$COMMIT_LENGTH" -lt "$MIN_LENGTH" ]; then
    echo "Warning: Commit message is quite short ($COMMIT_LENGTH characters)."
    echo "Consider being more descriptive."
fi


echo "Commit Message Validated."
exit 0