#!/bin/sh
# Pre Commit Hook can only see files in staging area

echo "Make sure your commit message is clear and meaningful!"
echo "Pre-Commit Hook: Checking before commit..."

BLOCKED_FILE="blocked_file.txt"
BLOCKED_FILES="\.env$|\.secret$|\.config$|\.log$|\.txt$"

# Only block commit if the file is staged
if git diff --cached --name-only | grep -q "$BLOCKED_FILE"; then
    echo "Commit Blocked: '$BLOCKED_FILE' is staged for commit."
    echo "Please remove it from the staging area before committing."
    exit 1
fi

# Check for blocked file extensions
if git diff --cached --name-only | grep -E -q "$BLOCKED_FILES"; then
	echo "Commit Blocked: One or more files with forbidden extensiosn are staged."
	echo "Blocked Extensions: $BLOCKED_FILES"
	exit 1
fi

exit 0